Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/medusa-2VgPi4zZ-py3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.cache/pypoetry/virtualenvs/medusa-2VgPi4zZ-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.cache/pypoetry/virtualenvs/medusa-2VgPi4zZ-py3.10/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/.cache/pypoetry/virtualenvs/medusa-2VgPi4zZ-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.cache/pypoetry/virtualenvs/medusa-2VgPi4zZ-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.cache/pypoetry/virtualenvs/medusa-2VgPi4zZ-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from medusa.data import get_example_image

for p in timer_.iter(params):

    if p["model_cls"] == YunetDetector and p["device"] == "cuda":
        continue

    model = p["model_cls"](device=p["device"])
    img = get_example_image(device=p["device"])
    img = img.repeat(p["batch_size"], 1, 1, 1)

    with torch.inference_mode():
        timer_.time(model, [img], n_warmup=3, repeats=20, params=p)

    torch.cuda.empty_cache()

df_detect = timer_.to_df()
------------------

----- stderr -----
  0%|          | 0/40 [00:00<?, ?it/s]
----- stderr -----
  0%|          | 0/40 [00:00<?, ?it/s]
----- stderr -----

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mRuntimeError[0m                              Traceback (most recent call last)
Cell [0;32mIn[2], line 9[0m
[1;32m      6[0m     [38;5;28;01mcontinue[39;00m
[1;32m      8[0m model [38;5;241m=[39m p[[38;5;124m"[39m[38;5;124mmodel_cls[39m[38;5;124m"[39m](device[38;5;241m=[39mp[[38;5;124m"[39m[38;5;124mdevice[39m[38;5;124m"[39m])
[0;32m----> 9[0m img [38;5;241m=[39m [43mget_example_image[49m[43m([49m[43mdevice[49m[38;5;241;43m=[39;49m[43mp[49m[43m[[49m[38;5;124;43m"[39;49m[38;5;124;43mdevice[39;49m[38;5;124;43m"[39;49m[43m][49m[43m)[49m
[1;32m     10[0m img [38;5;241m=[39m img[38;5;241m.[39mrepeat(p[[38;5;124m"[39m[38;5;124mbatch_size[39m[38;5;124m"[39m], [38;5;241m1[39m, [38;5;241m1[39m, [38;5;241m1[39m)
[1;32m     12[0m [38;5;28;01mwith[39;00m torch[38;5;241m.[39minference_mode():

File [0;32m~/work/medusa/medusa/medusa/data/example_data.py:79[0m, in [0;36mget_example_image[0;34m(n_faces, load, device, channels_last, dtype)[0m
[1;32m     77[0m     imgs[38;5;241m.[39mappend(f)
[1;32m     78[0m [38;5;28;01melse[39;00m:
[0;32m---> 79[0m     img [38;5;241m=[39m [43mread_image[49m[43m([49m[38;5;28;43mstr[39;49m[43m([49m[43mf[49m[43m)[49m[43m)[49m[38;5;241;43m.[39;49m[43mto[49m[43m([49m[43mdevice[49m[43m)[49m
[1;32m     80[0m     [38;5;28;01mif[39;00m channels_last:
[1;32m     81[0m         img [38;5;241m=[39m img[38;5;241m.[39mpermute([38;5;241m1[39m, [38;5;241m2[39m, [38;5;241m0[39m)

File [0;32m~/.cache/pypoetry/virtualenvs/medusa-2VgPi4zZ-py3.10/lib/python3.10/site-packages/torch/cuda/__init__.py:247[0m, in [0;36m_lazy_init[0;34m()[0m
[1;32m    245[0m [38;5;28;01mif[39;00m [38;5;124m'[39m[38;5;124mCUDA_MODULE_LOADING[39m[38;5;124m'[39m [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m os[38;5;241m.[39menviron:
[1;32m    246[0m     os[38;5;241m.[39menviron[[38;5;124m'[39m[38;5;124mCUDA_MODULE_LOADING[39m[38;5;124m'[39m] [38;5;241m=[39m [38;5;124m'[39m[38;5;124mLAZY[39m[38;5;124m'[39m
[0;32m--> 247[0m [43mtorch[49m[38;5;241;43m.[39;49m[43m_C[49m[38;5;241;43m.[39;49m[43m_cuda_init[49m[43m([49m[43m)[49m
[1;32m    248[0m [38;5;66;03m# Some of the queued calls may reentrantly call _lazy_init();[39;00m
[1;32m    249[0m [38;5;66;03m# we need to just return without initializing in that case.[39;00m
[1;32m    250[0m [38;5;66;03m# However, we must not let any *other* threads in![39;00m
[1;32m    251[0m _tls[38;5;241m.[39mis_initializing [38;5;241m=[39m [38;5;28;01mTrue[39;00m

[0;31mRuntimeError[0m: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

