Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/medusa-2VgPi4zZ-py3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.cache/pypoetry/virtualenvs/medusa-2VgPi4zZ-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.cache/pypoetry/virtualenvs/medusa-2VgPi4zZ-py3.10/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/.cache/pypoetry/virtualenvs/medusa-2VgPi4zZ-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.cache/pypoetry/virtualenvs/medusa-2VgPi4zZ-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.cache/pypoetry/virtualenvs/medusa-2VgPi4zZ-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
N = data_4d.v.shape[0]
vertex_colors = torch.rand(N, V, 3, device='cuda')
renderer.render(f_out, data_4d, overlay=vertex_colors)

Video(f_out, embed=True)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mRuntimeError[0m                              Traceback (most recent call last)
Cell [0;32mIn[11], line 2[0m
[1;32m      1[0m N [38;5;241m=[39m data_4d[38;5;241m.[39mv[38;5;241m.[39mshape[[38;5;241m0[39m]
[0;32m----> 2[0m vertex_colors [38;5;241m=[39m [43mtorch[49m[38;5;241;43m.[39;49m[43mrand[49m[43m([49m[43mN[49m[43m,[49m[43m [49m[43mV[49m[43m,[49m[43m [49m[38;5;241;43m3[39;49m[43m,[49m[43m [49m[43mdevice[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mcuda[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      3[0m renderer[38;5;241m.[39mrender(f_out, data_4d, overlay[38;5;241m=[39mvertex_colors)
[1;32m      5[0m Video(f_out, embed[38;5;241m=[39m[38;5;28;01mTrue[39;00m)

File [0;32m~/.cache/pypoetry/virtualenvs/medusa-2VgPi4zZ-py3.10/lib/python3.10/site-packages/torch/cuda/__init__.py:247[0m, in [0;36m_lazy_init[0;34m()[0m
[1;32m    245[0m [38;5;28;01mif[39;00m [38;5;124m'[39m[38;5;124mCUDA_MODULE_LOADING[39m[38;5;124m'[39m [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m os[38;5;241m.[39menviron:
[1;32m    246[0m     os[38;5;241m.[39menviron[[38;5;124m'[39m[38;5;124mCUDA_MODULE_LOADING[39m[38;5;124m'[39m] [38;5;241m=[39m [38;5;124m'[39m[38;5;124mLAZY[39m[38;5;124m'[39m
[0;32m--> 247[0m [43mtorch[49m[38;5;241;43m.[39;49m[43m_C[49m[38;5;241;43m.[39;49m[43m_cuda_init[49m[43m([49m[43m)[49m
[1;32m    248[0m [38;5;66;03m# Some of the queued calls may reentrantly call _lazy_init();[39;00m
[1;32m    249[0m [38;5;66;03m# we need to just return without initializing in that case.[39;00m
[1;32m    250[0m [38;5;66;03m# However, we must not let any *other* threads in![39;00m
[1;32m    251[0m _tls[38;5;241m.[39mis_initializing [38;5;241m=[39m [38;5;28;01mTrue[39;00m

[0;31mRuntimeError[0m: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

